# PreProcessing

#### 1. Imports

In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

#### 2. Load data

In [4]:
df = pd.read_csv("../data/raw/cardekho_dataset.csv")

print(df.shape)
df.head()

(15411, 14)

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

#### 3. Remove useless columns

In [5]:
df = df.drop(columns=["Unnamed: 0", "car_name"])

print(df.shape)
df.head()

(15411, 12)

,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

#### 4. Remove invalid seats

In [6]:
print("Rows before:", len(df))

df = df[df["seats"] > 0]

print("Rows after:", len(df))

Rows before: 15411
Rows after: 15409

#### 5. Remove unrealistic KM value

In [7]:
print("Maximum KM before:", df["km_driven"].max())

df = df[df["km_driven"] < 1_000_000]

print("Maximum KM after:", df["km_driven"].max())
print("Rows after:", len(df))

Maximum KM before: 3800000
Maximum KM after: 950000
Rows after: 15407

#### 6. Check duplicates

In [9]:
print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Rows after duplicate removal:", len(df))

Duplicate rows: 167
Rows after duplicate removal: 15240

#### 7. Define target and features

In [10]:
target = "selling_price"

X = df.drop(columns=[target])
y = df[target]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (15240, 11)
y shape: (15240,)

#### 8. Train/test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (12192, 11)
Testing data: (3048, 11)

#### 9. Identify categorical and numerical columns

In [12]:
categorical_features = [
    "brand",
    "model",
    "seller_type",
    "fuel_type",
    "transmission_type"
]

numerical_features = [
    "vehicle_age",
    "km_driven",
    "mileage",
    "engine",
    "max_power",
    "seats"
]

#### 10. Create encoder

In [13]:
categorical_transformer = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

#### 11. Numerical scaler

In [14]:
numerical_transformer = StandardScaler()

#### 12. Combine preprocessing

In [15]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numerical_transformer,
            numerical_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

#### 13. Fit preprocessing

In [16]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

#### 14. Check processed data

In [17]:
print("Original training shape:", X_train.shape)
print("Processed training shape:", X_train_processed.shape)

print("Original testing shape:", X_test.shape)
print("Processed testing shape:", X_test_processed.shape)

Original training shape: (12192, 11)
Processed training shape: (12192, 164)
Original testing shape: (3048, 11)
Processed testing shape: (3048, 164)

#### 15. Get Features Names

In [18]:
feature_names = preprocessor.get_feature_names_out()

print("Number of features:", len(feature_names))

print(feature_names[:50])

Number of features: 164
['num__vehicle_age' 'num__km_driven' 'num__mileage' 'num__engine'
 'num__max_power' 'num__seats' 'cat__brand_Audi' 'cat__brand_BMW'
 'cat__brand_Bentley' 'cat__brand_Datsun' 'cat__brand_Force'
 'cat__brand_Ford' 'cat__brand_Honda' 'cat__brand_Hyundai'
 'cat__brand_ISUZU' 'cat__brand_Isuzu' 'cat__brand_Jaguar'
 'cat__brand_Jeep' 'cat__brand_Kia' 'cat__brand_Land Rover'
 'cat__brand_Lexus' 'cat__brand_MG' 'cat__brand_Mahindra'
 'cat__brand_Maruti' 'cat__brand_Maserati' 'cat__brand_Mercedes-AMG'
 'cat__brand_Mercedes-Benz' 'cat__brand_Mini' 'cat__brand_Nissan'
 'cat__brand_Porsche' 'cat__brand_Renault' 'cat__brand_Skoda'
 'cat__brand_Tata' 'cat__brand_Toyota' 'cat__brand_Volkswagen'
 'cat__brand_Volvo' 'cat__model_3' 'cat__model_5' 'cat__model_6'
 'cat__model_7' 'cat__model_A4' 'cat__model_A6' 'cat__model_A8'
 'cat__model_Alto' 'cat__model_Altroz' 'cat__model_Alturas'
 'cat__model_Amaze' 'cat__model_Aspire' 'cat__model_Aura'
 'cat__model_Baleno']

#### 16. Convert to DataFrame

In [19]:
X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=feature_names,
    index=X_train.index
)

X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=feature_names,
    index=X_test.index
)

#### 17. Save processed datasets

In [21]:
train_processed = X_train_processed_df.copy()
train_processed["selling_price"] = y_train

test_processed = X_test_processed_df.copy()
test_processed["selling_price"] = y_test

train_processed.to_csv(
    "../data/processed/train_processed.csv",
    index=False
)

test_processed.to_csv(
    "../data/processed/test_processed.csv",
    index=False
)

print("Processed datasets saved.")

Processed datasets saved.

#### 18. Save the preprocessor

This is extremely important for the backend.

In [22]:
import joblib

joblib.dump(
    preprocessor,
    "../models/preprocessor.pkl"
)

print("Preprocessor saved successfully.")

Preprocessor saved successfully.